{
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  },
  "colab": {
   "provenance": [],
   "toc_visible": true
  }
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Deteksi Kemiripan Wajah dengan PCA/SVD\n",
    "## Implementasi Aljabar Linear — Eigenvalue, Eigenvector, dan Principal Component Analysis\n",
    "\n",
    "**Dataset**: FG-NET (Face and Gesture Recognition Network)  \n",
    "**Metode**: PCA via Singular Value Decomposition (SVD)  \n",
    "**Referensi**: Modul Aljabar Linear — Eigenvector, Eigenvalue, PCA, SVD\n",
    "\n",
    "---\n",
    "### Alur Implementasi (sesuai panduan)\n",
    "1. Setup & Install\n",
    "2. Load & Reorganisasi Dataset FG-NET\n",
    "3. EDA Awal (Exploratory Data Analysis)\n",
    "4. Preprocessing & Centering\n",
    "5. Implementasi PCA via SVD dari Scratch\n",
    "6. Visualisasi Eigenfaces\n",
    "7. Kompresi Citra & Evaluasi (MSE, PSNR, SSIM)\n",
    "8. EDA Setelah Kompresi\n",
    "9. Deteksi Kemiripan Wajah (Cosine Similarity)\n",
    "10. Identifikasi Wajah dari Database"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Setup & Install"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install dependensi\n",
    "!pip install opencv-python-headless scikit-learn numpy matplotlib seaborn pillow scipy -q\n",
    "\n",
    "# Clone repository (ganti URL sesuai repo kamu)\n",
    "# !git clone https://github.com/USERNAME/face-similarity-pca.git\n",
    "# %cd face-similarity-pca\n",
    "\n",
    "# ATAU: upload images.zip langsung ke Colab\n",
    "# from google.colab import files\n",
    "# uploaded = files.upload()  # upload images.zip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "import cv2\n",
    "import os\n",
    "import re\n",
    "import zipfile\n",
    "import shutil\n",
    "import pickle\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Matplotlib inline\n",
    "%matplotlib inline\n",
    "plt.rcParams['figure.dpi'] = 120\n",
    "plt.rcParams['font.family'] = 'DejaVu Sans'\n",
    "\n",
    "print('Setup selesai. Library berhasil dimuat.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Konstanta & Konfigurasi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "IMG_SIZE     = (100, 100)  # width x height\n",
    "N_COMPONENTS = 50          # jumlah principal components\n",
    "DATASET_PATH = 'dataset/'  # path dataset setelah reorganisasi\n",
    "ZIP_PATH     = 'images.zip'  # path file zip FG-NET\n",
    "\n",
    "print(f'Ukuran citra  : {IMG_SIZE}')\n",
    "print(f'n_components  : {N_COMPONENTS}')\n",
    "print(f'Piksel/gambar : {IMG_SIZE[0]*IMG_SIZE[1]}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Reorganisasi Dataset FG-NET\n",
    "\n",
    "Format FG-NET: `images/XXXAYYY.JPG`  \n",
    "- `XXX` = ID orang (001–082)  \n",
    "- `A` = huruf pemisah  \n",
    "- `YYY` = umur saat foto diambil\n",
    "\n",
    "Kita reorganisasi ke struktur per-orang: `dataset/001/001A02.JPG`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def reorganize_fgnet(zip_path: str, output_dir: str = 'dataset/') -> dict:\n",
    "    \"\"\"\n",
    "    Ekstrak dan reorganisasi dataset FG-NET dari flat ZIP\n",
    "    ke struktur per-orang.\n",
    "    \"\"\"\n",
    "    raw_dir = 'images_raw/'\n",
    "    os.makedirs(raw_dir, exist_ok=True)\n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "    print(f'Mengekstrak {zip_path}...')\n",
    "    with zipfile.ZipFile(zip_path, 'r') as z:\n",
    "        z.extractall(raw_dir)\n",
    "\n",
    "    # Cari folder images/\n",
    "    src_folder = None\n",
    "    for root, dirs, files in os.walk(raw_dir):\n",
    "        if any(f.lower().endswith('.jpg') for f in files):\n",
    "            src_folder = root\n",
    "            break\n",
    "\n",
    "    if src_folder is None:\n",
    "        raise FileNotFoundError('Tidak ada file JPG ditemukan dalam ZIP')\n",
    "\n",
    "    pattern = re.compile(r'^(\\d{3})A\\d+[a-z]?\\.JPG$', re.IGNORECASE)\n",
    "    moved, skipped, persons = 0, 0, set()\n",
    "\n",
    "    for fname in sorted(os.listdir(src_folder)):\n",
    "        m = pattern.match(fname)\n",
    "        if not m:\n",
    "            skipped += 1\n",
    "            continue\n",
    "        person_id  = m.group(1)\n",
    "        person_dir = os.path.join(output_dir, person_id)\n",
    "        os.makedirs(person_dir, exist_ok=True)\n",
    "        shutil.copy2(\n",
    "            os.path.join(src_folder, fname),\n",
    "            os.path.join(person_dir, fname)\n",
    "        )\n",
    "        persons.add(person_id)\n",
    "        moved += 1\n",
    "\n",
    "    print(f'Selesai! {moved} file → {len(persons)} orang')\n",
    "    return {'moved': moved, 'skipped': skipped, 'persons': sorted(persons)}\n",
    "\n",
    "\n",
    "# Jalankan reorganisasi\n",
    "if not os.path.isdir(DATASET_PATH) or len(os.listdir(DATASET_PATH)) == 0:\n",
    "    result = reorganize_fgnet(ZIP_PATH, DATASET_PATH)\n",
    "else:\n",
    "    n_persons = len(os.listdir(DATASET_PATH))\n",
    "    print(f'Dataset sudah ada: {n_persons} orang')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Load Dataset\n",
    "\n",
    "Setiap gambar:\n",
    "1. Dibaca sebagai BGR\n",
    "2. Dikonversi ke grayscale\n",
    "3. Di-resize ke 100×100\n",
    "4. Dinormalisasi ke [0, 1]\n",
    "5. Di-flatten menjadi vektor 10.000 elemen"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_face_image(path: str, img_size=IMG_SIZE) -> np.ndarray:\n",
    "    \"\"\"Baca gambar → vektor float64 [0,1] shape (n,)\"\"\"\n",
    "    img  = cv2.imread(path)\n",
    "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "    resized = cv2.resize(gray, img_size)\n",
    "    return (resized.astype(np.float64) / 255.0).flatten()\n",
    "\n",
    "\n",
    "def load_dataset(dataset_path: str, img_size=IMG_SIZE):\n",
    "    \"\"\"Load semua gambar dari dataset/XXX/ → X, labels, paths\"\"\"\n",
    "    X, labels, paths = [], [], []\n",
    "    for pid in sorted(os.listdir(dataset_path)):\n",
    "        pdir = os.path.join(dataset_path, pid)\n",
    "        if not os.path.isdir(pdir): continue\n",
    "        for fname in sorted(os.listdir(pdir)):\n",
    "            if fname.lower().endswith(('.jpg','.jpeg','.png')):\n",
    "                fpath = os.path.join(pdir, fname)\n",
    "                try:\n",
    "                    X.append(load_face_image(fpath, img_size))\n",
    "                    labels.append(pid)\n",
    "                    paths.append(fpath)\n",
    "                except Exception: pass\n",
    "    return np.array(X), np.array(labels), paths\n",
    "\n",
    "\n",
    "print('Memuat dataset...')\n",
    "X, labels, paths = load_dataset(DATASET_PATH)\n",
    "print(f'Berhasil dimuat!')\n",
    "print(f'  Shape X   : {X.shape}  (gambar × piksel)')\n",
    "print(f'  Orang     : {len(np.unique(labels))}')\n",
    "print(f'  Gambar    : {len(X)}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. EDA Awal (Exploratory Data Analysis)\n",
    "\n",
    "Sesuai Tahap 2 dari panduan: memahami karakteristik citra sebelum PCA."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── 5a. Statistik dasar ──────────────────────────────────────────────\n",
    "print('=== EDA AWAL DATASET ===')\n",
    "print(f'Dimensi matriks X      : {X.shape}')\n",
    "print(f'Total piksel per gambar: {X.shape[1]:,}')\n",
    "print(f'Min piksel             : {X.min():.4f}')\n",
    "print(f'Max piksel             : {X.max():.4f}')\n",
    "print(f'Mean piksel            : {X.mean():.4f}')\n",
    "print(f'Std dev piksel         : {X.std():.4f}')\n",
    "print(f'Median piksel          : {np.median(X):.4f}')\n",
    "\n",
    "unique_ids, counts = np.unique(labels, return_counts=True)\n",
    "print(f'\\nGambar per orang (min/max/mean): {counts.min()}/{counts.max()}/{counts.mean():.1f}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── 5b. Visualisasi EDA ──────────────────────────────────────────────\n",
    "fig = plt.figure(figsize=(16, 10))\n",
    "gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)\n",
    "\n",
    "# Distribusi gambar per orang\n",
    "ax1 = fig.add_subplot(gs[0, :])\n",
    "ax1.bar(range(len(unique_ids)), counts, color='steelblue', edgecolor='none', alpha=0.85)\n",
    "ax1.axhline(counts.mean(), color='orange', linestyle='--', linewidth=2,\n",
    "            label=f'Rata-rata: {counts.mean():.1f} foto')\n",
    "ax1.set_xlabel('Person ID'); ax1.set_ylabel('Jumlah Foto')\n",
    "ax1.set_title('Distribusi Jumlah Foto per Orang (FG-NET Dataset)')\n",
    "ax1.set_xticks(range(0, len(unique_ids), 5))\n",
    "ax1.set_xticklabels(unique_ids[::5], rotation=45, fontsize=8)\n",
    "ax1.legend(); ax1.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# Histogram intensitas piksel\n",
    "ax2 = fig.add_subplot(gs[1, 0])\n",
    "flat = X.flatten()\n",
    "ax2.hist(flat, bins=80, color='steelblue', alpha=0.8, edgecolor='none')\n",
    "ax2.axvline(flat.mean(), color='orange', linestyle='--', label=f'Mean={flat.mean():.3f}')\n",
    "ax2.set_xlabel('Nilai Piksel (0–1)'); ax2.set_ylabel('Frekuensi')\n",
    "ax2.set_title('Histogram Intensitas Dataset')\n",
    "ax2.legend(); ax2.grid(alpha=0.3)\n",
    "\n",
    "# Sample gambar asli\n",
    "ax3 = fig.add_subplot(gs[1, 1])\n",
    "sample_img = X[0].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "ax3.imshow(sample_img, cmap='gray')\n",
    "ax3.set_title(f'Sample: Person {labels[0]}\\n({os.path.basename(paths[0])})')\n",
    "ax3.axis('off')\n",
    "\n",
    "# Variasi antar piksel (std per piksel)\n",
    "ax4 = fig.add_subplot(gs[1, 2])\n",
    "std_per_pixel = X.std(axis=0).reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "im = ax4.imshow(std_per_pixel, cmap='hot')\n",
    "plt.colorbar(im, ax=ax4)\n",
    "ax4.set_title('Std Dev per Piksel\\n(area terang = variasi tinggi)')\n",
    "ax4.axis('off')\n",
    "\n",
    "fig.suptitle('EDA Awal Dataset FG-NET', fontsize=14, fontweight='bold')\n",
    "plt.savefig('eda_awal.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('EDA awal selesai.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Centering Data (Tahap 4 Panduan)\n",
    "\n",
    "$$X_c = X - \\mu$$\n",
    "\n",
    "μ = **mean face** (wajah rata-rata dari seluruh dataset)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Hitung mean face\n",
    "mu = np.mean(X, axis=0)       # shape: (10000,)\n",
    "Xc = X - mu                   # shape: (1002, 10000)\n",
    "\n",
    "print(f'Shape X    : {X.shape}')\n",
    "print(f'Shape mu   : {mu.shape}')\n",
    "print(f'Shape Xc   : {Xc.shape}')\n",
    "print(f'Mean Xc    : {Xc.mean():.2e}  (mendekati nol ✓)')\n",
    "\n",
    "# Visualisasi mean face\n",
    "fig, axes = plt.subplots(1, 3, figsize=(10, 3.5))\n",
    "axes[0].imshow(X[0].reshape(IMG_SIZE[1], IMG_SIZE[0]), cmap='gray')\n",
    "axes[0].set_title(f'Gambar Asli\\nPerson {labels[0]}')\n",
    "axes[0].axis('off')\n",
    "\n",
    "mean_img = mu.reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "axes[1].imshow(mean_img, cmap='gray')\n",
    "axes[1].set_title('Mean Face (μ)\\nWajah Rata-Rata')\n",
    "axes[1].axis('off')\n",
    "\n",
    "centered_img = Xc[0].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "axes[2].imshow(centered_img, cmap='seismic',\n",
    "               vmin=-centered_img.max(), vmax=centered_img.max())\n",
    "axes[2].set_title('Setelah Centering (Xc)\\nX - μ')\n",
    "axes[2].axis('off')\n",
    "\n",
    "fig.suptitle('Tahap Centering Data', fontsize=12, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('centering.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Implementasi PCA via SVD dari Scratch\n",
    "\n",
    "**Tanpa sklearn** — mengimplementasikan langsung sesuai panduan:\n",
    "\n",
    "$$X_c = U \\Sigma V^T$$\n",
    "\n",
    "Eigenvalue: $\\lambda_i = \\sigma_i^2 / (m-1)$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "\n",
    "print(f'Menjalankan SVD pada Xc ({Xc.shape})...')\n",
    "print('(Ini bisa memakan waktu 10–30 detik)')\n",
    "\n",
    "t0 = time.time()\n",
    "# SVD — inti dari implementasi PCA kita\n",
    "# full_matrices=False → Reduced SVD (lebih efisien memori)\n",
    "U, sigma, VT = np.linalg.svd(Xc, full_matrices=False)\n",
    "t_elapsed = time.time() - t0\n",
    "\n",
    "print(f'SVD selesai dalam {t_elapsed:.1f} detik')\n",
    "print(f'\\nShape U      : {U.shape}   (left singular vectors)')\n",
    "print(f'Shape sigma  : {sigma.shape} (singular values)')\n",
    "print(f'Shape VT     : {VT.shape}  (right singular vectors = eigenfaces)')\n",
    "print(f'\\nTop-10 singular values: {sigma[:10].round(2)}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Hitung eigenvalue dari singular value\n",
    "m = Xc.shape[0]\n",
    "eigenvalues = (sigma ** 2) / (m - 1)\n",
    "\n",
    "# Explained variance ratio\n",
    "ev_total = np.sum(eigenvalues)\n",
    "evr      = eigenvalues / ev_total  # per komponen\n",
    "cumevr   = np.cumsum(evr)          # kumulatif\n",
    "\n",
    "# Komponen yang dipilih\n",
    "k = N_COMPONENTS\n",
    "V_k = VT[:k]          # (k, n) — eigenvectors (eigenfaces)\n",
    "\n",
    "print(f'=== Eigenvalue Report ===')\n",
    "print(f'k = {k} komponen dipilih')\n",
    "print(f'Explained variance dengan k={k}: {cumevr[k-1]*100:.2f}%')\n",
    "print(f'\\nKomponen minimum untuk:')\n",
    "for thresh in [0.80, 0.90, 0.95, 0.99]:\n",
    "    idx = np.where(cumevr >= thresh)[0]\n",
    "    k_need = idx[0]+1 if len(idx) > 0 else 'perlu > 1000'\n",
    "    print(f'  {int(thresh*100)}% variance: {k_need} komponen')\n",
    "\n",
    "print(f'\\nTop-5 eigenvalues: {eigenvalues[:5].round(3)}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Scree Plot & Cumulative Explained Variance ────────────────────────\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "# Scree Plot\n",
    "k_show = 80\n",
    "ax1.plot(range(1, k_show+1), eigenvalues[:k_show], 'o-',\n",
    "         color='steelblue', markersize=5, linewidth=2)\n",
    "ax1.set_xlabel('Principal Component ke-', fontsize=11)\n",
    "ax1.set_ylabel('Eigenvalue (λ)', fontsize=11)\n",
    "ax1.set_title('Scree Plot — Eigenvalue per Komponen', fontsize=12)\n",
    "ax1.set_yscale('log')\n",
    "ax1.grid(alpha=0.3)\n",
    "# Elbow\n",
    "diffs = np.diff(eigenvalues[:k_show])\n",
    "elbow = int(np.argmin(diffs)) + 1\n",
    "ax1.axvline(elbow, color='red', linestyle='--', alpha=0.7,\n",
    "            label=f'Elbow ≈ PC{elbow}')\n",
    "ax1.axvline(k, color='orange', linestyle=':', linewidth=2,\n",
    "            label=f'k={k} dipilih')\n",
    "ax1.legend()\n",
    "\n",
    "# Cumulative EVR\n",
    "ax2.plot(range(1, len(cumevr)+1), cumevr*100,\n",
    "         color='green', linewidth=2.5)\n",
    "ax2.fill_between(range(1, len(cumevr)+1), cumevr*100, alpha=0.15, color='green')\n",
    "for thresh in [80, 90, 95, 99]:\n",
    "    idx = np.where(cumevr*100 >= thresh)[0]\n",
    "    if len(idx):\n",
    "        ax2.axhline(thresh, color='gray', linestyle=':', alpha=0.6)\n",
    "        ax2.text(2, thresh+0.5, f'{thresh}% (k={idx[0]+1})', fontsize=9, color='gray')\n",
    "ax2.axvline(k, color='orange', linestyle=':', linewidth=2, label=f'k={k} → {cumevr[k-1]*100:.1f}%')\n",
    "ax2.set_xlabel('Jumlah Komponen (k)', fontsize=11)\n",
    "ax2.set_ylabel('Cumulative Explained Variance (%)', fontsize=11)\n",
    "ax2.set_title('Cumulative Explained Variance', fontsize=12)\n",
    "ax2.set_xlim(1, min(200, len(cumevr)))\n",
    "ax2.set_ylim(0, 105)\n",
    "ax2.grid(alpha=0.3)\n",
    "ax2.legend()\n",
    "\n",
    "fig.suptitle('Analisis Eigenvalue — Panduan Pemilihan k', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('scree_plot.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Proyeksi Data ke Ruang PCA (Tahap 9)\n",
    "\n",
    "$$Z = X_c \\cdot V_k^T$$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Proyeksi: Z = Xc · V_k^T\n",
    "Z = Xc @ V_k.T     # (m, k) = (1002, 50)\n",
    "\n",
    "print(f'Shape Xc   : {Xc.shape}')\n",
    "print(f'Shape V_k.T: {V_k.T.shape}')\n",
    "print(f'Shape Z    : {Z.shape}  ← representasi terkompresi')\n",
    "print(f'\\nSetiap wajah: {Xc.shape[1]} piksel → {k} nilai (kompresi {Xc.shape[1]/k:.0f}x)')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualisasi PC1 vs PC2 (2D)\n",
    "fig, ax = plt.subplots(figsize=(10, 7))\n",
    "\n",
    "# Plot 20 orang pertama dengan warna berbeda\n",
    "n_plot = 20\n",
    "colors = plt.cm.tab20(np.linspace(0, 1, n_plot))\n",
    "\n",
    "for i, pid in enumerate(np.unique(labels)[:n_plot]):\n",
    "    mask = labels == pid\n",
    "    ax.scatter(Z[mask, 0], Z[mask, 1], c=[colors[i]], label=f'P{pid}',\n",
    "               alpha=0.7, s=40, edgecolor='none')\n",
    "\n",
    "ax.set_xlabel('PC1', fontsize=12)\n",
    "ax.set_ylabel('PC2', fontsize=12)\n",
    "ax.set_title(f'Proyeksi Wajah ke Ruang PCA (PC1 vs PC2)\\n'\n",
    "             f'{n_plot} orang pertama dari 82', fontsize=12)\n",
    "ax.legend(loc='upper right', fontsize=7, ncol=2)\n",
    "ax.grid(alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('pca_space.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Visualisasi Eigenfaces"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "n_show = 20\n",
    "cols   = 5\n",
    "rows   = int(np.ceil(n_show / cols))\n",
    "\n",
    "fig, axes = plt.subplots(rows, cols, figsize=(cols*2.8, rows*3))\n",
    "\n",
    "for i, ax in enumerate(axes.flat):\n",
    "    if i < n_show:\n",
    "        ef = V_k[i].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "        ef_norm = (ef - ef.min()) / (ef.max() - ef.min() + 1e-8)\n",
    "        ax.imshow(ef_norm, cmap='gray')\n",
    "        ax.set_title(f'PC{i+1}  ({evr[i]*100:.1f}%)', fontsize=9)\n",
    "    ax.axis('off')\n",
    "\n",
    "fig.suptitle(f'Top-{n_show} Eigenfaces — Arah Variasi Utama\\n'\n",
    "             f'(Eigenvectors dari matriks kovarians wajah)',\n",
    "             fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('eigenfaces.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "# Mean face\n",
    "fig, ax = plt.subplots(figsize=(3, 3))\n",
    "ax.imshow(mu.reshape(IMG_SIZE[1], IMG_SIZE[0]), cmap='gray')\n",
    "ax.set_title('Mean Face (μ)\\nWajah Rata-Rata Dataset', fontsize=10)\n",
    "ax.axis('off')\n",
    "plt.tight_layout()\n",
    "plt.savefig('mean_face.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Rekonstruksi Citra & Evaluasi (Tahap 10–11)\n",
    "\n",
    "$$\\hat{X} = Z \\cdot V_k^T + \\mu$$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fungsi metrik evaluasi\n",
    "def compute_mse(orig, recon):\n",
    "    return float(np.mean((orig - recon) ** 2))\n",
    "\n",
    "def compute_psnr(orig, recon, max_val=1.0):\n",
    "    err = compute_mse(orig, recon)\n",
    "    return float('inf') if err == 0 else float(10 * np.log10(max_val**2 / err))\n",
    "\n",
    "def compute_ssim(x, y, k1=0.01, k2=0.03, data_range=1.0):\n",
    "    c1 = (k1*data_range)**2; c2 = (k2*data_range)**2\n",
    "    mu_x, mu_y = np.mean(x), np.mean(y)\n",
    "    s2x, s2y   = np.var(x), np.var(y)\n",
    "    sxy = np.mean((x-mu_x)*(y-mu_y))\n",
    "    return float(((2*mu_x*mu_y+c1)*(2*sxy+c2)) / ((mu_x**2+mu_y**2+c1)*(s2x+s2y+c2)))\n",
    "\n",
    "def compression_ratio(n_pixels, k, m_samples):\n",
    "    return (m_samples * n_pixels) / (n_pixels*k + m_samples*k + n_pixels)\n",
    "\n",
    "\n",
    "# Rekonstruksi dengan k=50\n",
    "X_hat = Z @ V_k + mu         # (m, n)\n",
    "\n",
    "# Evaluasi pada 1 gambar sample\n",
    "idx = 0\n",
    "mse_v   = compute_mse(X[idx], X_hat[idx])\n",
    "psnr_v  = compute_psnr(X[idx], X_hat[idx])\n",
    "ssim_v  = compute_ssim(X[idx], X_hat[idx])\n",
    "cr_v    = compression_ratio(X.shape[1], k, X.shape[0])\n",
    "ev_pct  = cumevr[k-1] * 100\n",
    "\n",
    "print(f'=== Evaluasi Rekonstruksi (k={k}) ===')\n",
    "print(f'Explained Variance : {ev_pct:.2f}%')\n",
    "print(f'MSE                : {mse_v:.6f}')\n",
    "print(f'PSNR               : {psnr_v:.2f} dB  (>30=Baik, >40=Sangat Baik)')\n",
    "print(f'SSIM               : {ssim_v:.4f}  (mendekati 1=mirip)')\n",
    "print(f'Rasio Kompresi     : {cr_v:.2f}x')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Visualisasi rekonstruksi untuk berbagai k ─────────────────────────\n",
    "k_vals = [5, 10, 20, 30, 50, 75]\n",
    "k_vals = [kv for kv in k_vals if kv <= len(sigma)]\n",
    "\n",
    "fig, axes = plt.subplots(2, len(k_vals)+1, figsize=((len(k_vals)+1)*2.5, 5.5))\n",
    "\n",
    "sample_idx = 5  # gambar yang digunakan\n",
    "orig = X[sample_idx].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "\n",
    "# Kolom 0: gambar asli\n",
    "axes[0][0].imshow(orig, cmap='gray', vmin=0, vmax=1)\n",
    "axes[0][0].set_title('Original', fontsize=10, fontweight='bold')\n",
    "axes[0][0].axis('off')\n",
    "axes[1][0].axis('off')\n",
    "axes[1][0].text(0.5, 0.5, f'Person\\n{labels[sample_idx]}',\n",
    "                ha='center', va='center', transform=axes[1][0].transAxes, fontsize=9)\n",
    "\n",
    "for col, kv in enumerate(k_vals, 1):\n",
    "    V_kv  = VT[:kv]\n",
    "    z_kv  = Xc[sample_idx] @ V_kv.T\n",
    "    recon = np.clip(z_kv @ V_kv + mu, 0, 1).reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "    error_img = np.abs(orig - recon)\n",
    "    \n",
    "    mse_kv  = compute_mse(X[sample_idx], (z_kv @ V_kv + mu))\n",
    "    psnr_kv = compute_psnr(X[sample_idx], (z_kv @ V_kv + mu))\n",
    "    ev_kv   = cumevr[kv-1]*100\n",
    "    \n",
    "    axes[0][col].imshow(recon, cmap='gray', vmin=0, vmax=1)\n",
    "    axes[0][col].set_title(f'k={kv}\\n{ev_kv:.0f}%', fontsize=9)\n",
    "    axes[0][col].axis('off')\n",
    "    \n",
    "    axes[1][col].imshow(error_img, cmap='hot', vmin=0, vmax=0.3)\n",
    "    axes[1][col].set_title(f'PSNR={psnr_kv:.1f}dB\\nMSE={mse_kv:.4f}', fontsize=8)\n",
    "    axes[1][col].axis('off')\n",
    "\n",
    "fig.text(0.02, 0.75, 'Rekonstruksi', va='center', rotation='vertical', fontsize=11)\n",
    "fig.text(0.02, 0.25, 'Error Image', va='center', rotation='vertical', fontsize=11)\n",
    "fig.suptitle('Kompresi PCA — Efek Jumlah Komponen k', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('kompresi_berbagai_k.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Tabel evaluasi berbagai k ─────────────────────────────────────────\n",
    "import pandas as pd\n",
    "\n",
    "rows = []\n",
    "for kv in k_vals:\n",
    "    V_kv = VT[:kv]\n",
    "    Z_kv = Xc[:50] @ V_kv.T\n",
    "    Xhat_kv = Z_kv @ V_kv + mu\n",
    "    rows.append({\n",
    "        'k'                  : kv,\n",
    "        'Explained Var. (%)'  : f'{cumevr[kv-1]*100:.1f}',\n",
    "        'MSE'                 : f'{compute_mse(X[:50], Xhat_kv):.5f}',\n",
    "        'PSNR (dB)'           : f'{compute_psnr(X[:50], Xhat_kv):.2f}',\n",
    "        'SSIM'                : f'{np.mean([compute_ssim(X[:50][i], Xhat_kv[i]) for i in range(50)]):.4f}',\n",
    "        'Rasio Kompresi'      : f'{compression_ratio(X.shape[1], kv, X.shape[0]):.2f}x',\n",
    "    })\n",
    "\n",
    "df_eval = pd.DataFrame(rows)\n",
    "print('=== Tabel Evaluasi Rekonstruksi ===')\n",
    "print(df_eval.to_string(index=False))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. EDA Setelah Kompresi (Tahap 12)\n",
    "\n",
    "Membandingkan histogram asli vs rekonstruksi dan error image."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "idx = 0\n",
    "orig_vec  = X[idx]\n",
    "recon_vec = np.clip(X_hat[idx], 0, 1)\n",
    "orig_img  = orig_vec.reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "recon_img = recon_vec.reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "error_img = np.abs(orig_img - recon_img)\n",
    "\n",
    "fig, axes = plt.subplots(2, 3, figsize=(13, 8))\n",
    "\n",
    "axes[0][0].imshow(orig_img, cmap='gray', vmin=0, vmax=1)\n",
    "axes[0][0].set_title('Citra Asli (X)', fontsize=11); axes[0][0].axis('off')\n",
    "\n",
    "axes[0][1].imshow(recon_img, cmap='gray', vmin=0, vmax=1)\n",
    "axes[0][1].set_title(f'Rekonstruksi (k={k})\\nX̂ = Z·Vₖᵀ + μ', fontsize=11); axes[0][1].axis('off')\n",
    "\n",
    "im = axes[0][2].imshow(error_img, cmap='hot', vmin=0, vmax=0.3)\n",
    "axes[0][2].set_title(f'Error Image |X − X̂|\\nMSE={compute_mse(orig_vec,recon_vec):.5f}', fontsize=11)\n",
    "axes[0][2].axis('off')\n",
    "plt.colorbar(im, ax=axes[0][2], fraction=0.046)\n",
    "\n",
    "# Histogram perbandingan\n",
    "axes[1][0].hist(orig_img.flatten(), bins=50, color='steelblue', alpha=0.7, label='Asli')\n",
    "axes[1][0].hist(recon_img.flatten(), bins=50, color='salmon', alpha=0.7, label='Rekonstruksi')\n",
    "axes[1][0].set_xlabel('Nilai Piksel'); axes[1][0].set_ylabel('Frekuensi')\n",
    "axes[1][0].set_title('Histogram: Asli vs Rekonstruksi')\n",
    "axes[1][0].legend(); axes[1][0].grid(alpha=0.3)\n",
    "\n",
    "# Scatter plot piksel\n",
    "axes[1][1].scatter(orig_vec[:500], recon_vec[:500], alpha=0.3, s=10, color='steelblue')\n",
    "lims = [0, 1]\n",
    "axes[1][1].plot(lims, lims, 'r--', linewidth=1.5, label='y=x (sempurna)')\n",
    "axes[1][1].set_xlabel('Piksel Asli'); axes[1][1].set_ylabel('Piksel Rekonstruksi')\n",
    "axes[1][1].set_title('Scatter: Asli vs Rekonstruksi (500 piksel)')\n",
    "axes[1][1].legend(); axes[1][1].grid(alpha=0.3)\n",
    "\n",
    "# Error distribution\n",
    "axes[1][2].hist(error_img.flatten(), bins=60, color='salmon', edgecolor='none', alpha=0.8)\n",
    "axes[1][2].set_xlabel('|Error|'); axes[1][2].set_ylabel('Frekuensi')\n",
    "axes[1][2].set_title(f'Distribusi Error\\nPSNR={compute_psnr(orig_vec,recon_vec):.2f}dB, SSIM={compute_ssim(orig_vec,recon_vec):.4f}')\n",
    "axes[1][2].grid(alpha=0.3)\n",
    "\n",
    "fig.suptitle(f'EDA Setelah Kompresi PCA (k={k})', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('eda_kompresi.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Deteksi Kemiripan Wajah\n",
    "\n",
    "$$\\text{sim}(z_1, z_2) = \\frac{z_1 \\cdot z_2}{\\|z_1\\| \\|z_2\\|}$$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def cosine_similarity(z1, z2):\n",
    "    \"\"\"Cosine similarity antara dua vektor PCA.\"\"\"\n",
    "    n1, n2 = np.linalg.norm(z1), np.linalg.norm(z2)\n",
    "    if n1 == 0 or n2 == 0: return 0.0\n",
    "    return float(np.dot(z1, z2) / (n1 * n2))\n",
    "\n",
    "def euclidean_distance(z1, z2):\n",
    "    return float(np.linalg.norm(z1 - z2))\n",
    "\n",
    "\n",
    "# Test: bandingkan dua foto dari orang SAMA\n",
    "pid_test = '001'\n",
    "same_person_mask = labels == pid_test\n",
    "same_idx = np.where(same_person_mask)[0]\n",
    "print(f'Orang {pid_test} memiliki {sum(same_person_mask)} foto')\n",
    "\n",
    "if len(same_idx) >= 2:\n",
    "    i1, i2 = same_idx[0], same_idx[-1]\n",
    "    z1, z2 = Z[i1], Z[i2]\n",
    "    cos  = cosine_similarity(z1, z2)\n",
    "    euc  = euclidean_distance(z1, z2)\n",
    "    print(f'\\n[SAMA] {os.path.basename(paths[i1])} vs {os.path.basename(paths[i2])}')\n",
    "    print(f'  Cosine Similarity  : {cos:.4f}')\n",
    "    print(f'  Euclidean Distance : {euc:.4f}')\n",
    "\n",
    "# Test: bandingkan dua foto dari orang BERBEDA\n",
    "diff_mask = labels == '002'\n",
    "diff_idx  = np.where(diff_mask)[0]\n",
    "if len(diff_idx) >= 1:\n",
    "    i3 = same_idx[0]\n",
    "    i4 = diff_idx[0]\n",
    "    z3, z4 = Z[i3], Z[i4]\n",
    "    cos2 = cosine_similarity(z3, z4)\n",
    "    euc2 = euclidean_distance(z3, z4)\n",
    "    print(f'\\n[BEDA] Person 001 vs Person 002')\n",
    "    print(f'  Cosine Similarity  : {cos2:.4f}')\n",
    "    print(f'  Euclidean Distance : {euc2:.4f}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualisasi perbandingan 2 pasang\n",
    "THRESHOLD = 0.80\n",
    "\n",
    "fig, axes = plt.subplots(2, 3, figsize=(11, 7))\n",
    "\n",
    "# Pasangan 1: orang sama\n",
    "img_a = X[i1].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "img_b = X[i2].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "axes[0][0].imshow(img_a, cmap='gray'); axes[0][0].axis('off')\n",
    "axes[0][0].set_title(f'Wajah A\\n{os.path.basename(paths[i1])}', fontsize=9)\n",
    "axes[0][1].imshow(img_b, cmap='gray'); axes[0][1].axis('off')\n",
    "axes[0][1].set_title(f'Wajah B\\n{os.path.basename(paths[i2])}', fontsize=9)\n",
    "result_color_1 = 'green' if cos >= THRESHOLD else 'red'\n",
    "result_text_1  = 'MIRIP ✓' if cos >= THRESHOLD else 'BERBEDA ✗'\n",
    "axes[0][2].text(0.5, 0.6, f'{result_text_1}', ha='center', va='center',\n",
    "                transform=axes[0][2].transAxes, fontsize=16, fontweight='bold',\n",
    "                color=result_color_1)\n",
    "axes[0][2].text(0.5, 0.4, f'Cosine: {cos:.4f}', ha='center', va='center',\n",
    "                transform=axes[0][2].transAxes, fontsize=12)\n",
    "axes[0][2].text(0.5, 0.25, f'Threshold: {THRESHOLD}', ha='center', va='center',\n",
    "                transform=axes[0][2].transAxes, fontsize=10, color='gray')\n",
    "axes[0][2].set_title('Orang yang SAMA', fontsize=10); axes[0][2].axis('off')\n",
    "\n",
    "# Pasangan 2: orang berbeda\n",
    "img_c = X[i3].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "img_d = X[i4].reshape(IMG_SIZE[1], IMG_SIZE[0])\n",
    "axes[1][0].imshow(img_c, cmap='gray'); axes[1][0].axis('off')\n",
    "axes[1][0].set_title(f'Wajah C\\n{os.path.basename(paths[i3])}', fontsize=9)\n",
    "axes[1][1].imshow(img_d, cmap='gray'); axes[1][1].axis('off')\n",
    "axes[1][1].set_title(f'Wajah D\\n{os.path.basename(paths[i4])}', fontsize=9)\n",
    "result_color_2 = 'green' if cos2 >= THRESHOLD else 'red'\n",
    "result_text_2  = 'MIRIP ✓' if cos2 >= THRESHOLD else 'BERBEDA ✗'\n",
    "axes[1][2].text(0.5, 0.6, f'{result_text_2}', ha='center', va='center',\n",
    "                transform=axes[1][2].transAxes, fontsize=16, fontweight='bold',\n",
    "                color=result_color_2)\n",
    "axes[1][2].text(0.5, 0.4, f'Cosine: {cos2:.4f}', ha='center', va='center',\n",
    "                transform=axes[1][2].transAxes, fontsize=12)\n",
    "axes[1][2].text(0.5, 0.25, f'Threshold: {THRESHOLD}', ha='center', va='center',\n",
    "                transform=axes[1][2].transAxes, fontsize=10, color='gray')\n",
    "axes[1][2].set_title('Orang yang BERBEDA', fontsize=10); axes[1][2].axis('off')\n",
    "\n",
    "fig.suptitle(f'Deteksi Kemiripan Wajah — PCA/SVD (k={k})', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('hasil_kemiripan.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 13. Identifikasi Wajah dari Database"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def recognize_face(query_vec, Z_db, labels_db, threshold=0.80, top_n=5):\n",
    "    \"\"\"Cari wajah paling mirip dari database.\"\"\"\n",
    "    # Proyeksi query ke ruang PCA\n",
    "    z_q   = (query_vec - mu) @ V_k.T\n",
    "    # Hitung similarity ke semua wajah di DB\n",
    "    sims  = np.array([cosine_similarity(z_q, z) for z in Z_db])\n",
    "    top   = np.argsort(sims)[::-1][:top_n]\n",
    "    best  = top[0]\n",
    "    label = labels_db[best] if sims[best] >= threshold else 'Tidak dikenal'\n",
    "    return label, sims[best], top, sims\n",
    "\n",
    "\n",
    "# Query: gambar terakhir dari orang 001 (yang belum ada di training set)\n",
    "query_idx   = same_idx[-1]\n",
    "query_label = labels[query_idx]\n",
    "print(f'Query: {os.path.basename(paths[query_idx])} (Person {query_label})')\n",
    "\n",
    "pred_label, best_sim, top_idx, all_sims = recognize_face(\n",
    "    X[query_idx], Z, labels, threshold=0.80, top_n=5\n",
    ")\n",
    "\n",
    "print(f'\\nHasil Identifikasi: Person {pred_label}')\n",
    "print(f'Similarity terbaik: {best_sim:.4f}')\n",
    "print(f'\\nTop-5 kandidat:')\n",
    "for rank, idx in enumerate(top_idx, 1):\n",
    "    mark = ' ← BENAR' if labels[idx] == query_label else ''\n",
    "    print(f'  {rank}. Person {labels[idx]}  sim={all_sims[idx]:.4f}  {os.path.basename(paths[idx])}{mark}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualisasi Top-5 kandidat\n",
    "n_top = 5\n",
    "fig, axes = plt.subplots(1, n_top+1, figsize=((n_top+1)*2.5, 3.5))\n",
    "\n",
    "axes[0].imshow(X[query_idx].reshape(IMG_SIZE[1], IMG_SIZE[0]), cmap='gray')\n",
    "axes[0].set_title(f'QUERY\\nPerson {query_label}', fontsize=9, fontweight='bold')\n",
    "axes[0].axis('off')\n",
    "for sp in axes[0].spines.values():\n",
    "    sp.set_edgecolor('blue'); sp.set_linewidth(3)\n",
    "\n",
    "for rank, (idx, ax) in enumerate(zip(top_idx, axes[1:]), 1):\n",
    "    ax.imshow(X[idx].reshape(IMG_SIZE[1], IMG_SIZE[0]), cmap='gray')\n",
    "    correct = labels[idx] == query_label\n",
    "    color   = '#28a745' if correct else '#dc3545'\n",
    "    ax.set_title(f'#{rank} Person {labels[idx]}\\n{all_sims[idx]:.4f}', fontsize=9, color=color)\n",
    "    ax.axis('off')\n",
    "    for sp in ax.spines.values():\n",
    "        sp.set_edgecolor(color); sp.set_linewidth(3)\n",
    "\n",
    "fig.suptitle('Top-5 Kandidat dari Database (hijau=benar, merah=salah)', fontsize=11, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('identifikasi.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 14. Simpan Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle, os\n",
    "os.makedirs('models', exist_ok=True)\n",
    "\n",
    "model = {\n",
    "    'mu'          : mu,\n",
    "    'V_k'         : V_k,\n",
    "    'sigma'       : sigma,\n",
    "    'eigenvalues' : eigenvalues,\n",
    "    'evr'         : evr,\n",
    "    'cumevr'      : cumevr,\n",
    "    'k'           : k,\n",
    "    'img_size'    : IMG_SIZE,\n",
    "}\n",
    "with open('models/pca_model_notebook.pkl', 'wb') as f:\n",
    "    pickle.dump(model, f)\n",
    "\n",
    "db = {'Z': Z, 'labels': labels, 'paths': paths, 'img_size': IMG_SIZE}\n",
    "with open('models/face_database_notebook.pkl', 'wb') as f:\n",
    "    pickle.dump(db, f)\n",
    "\n",
    "print('Model disimpan ke models/')\n",
    "print(f'  pca_model_notebook.pkl   — model PCA (mu, V_k, eigenvalues, ...)')\n",
    "print(f'  face_database_notebook.pkl — proyeksi Z + labels')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 15. Ringkasan\n",
    "\n",
    "| Konsep | Peran |\n",
    "|---|---|\n",
    "| **Matriks X** | Data wajah mentah ∈ ℝ^(m×n) |\n",
    "| **Mean face μ** | Wajah rata-rata; digunakan untuk centering |\n",
    "| **Centering Xc=X-μ** | Membuat data berpusat di nol |\n",
    "| **SVD: Xc=UΣVᵀ** | Dekomposisi matriks — inti PCA |\n",
    "| **Eigenvalue λ=σ²/(m-1)** | Besar informasi per komponen |\n",
    "| **Eigenvector V_k** | Arah komponen utama = **eigenfaces** |\n",
    "| **Proyeksi Z=Xc·Vₖᵀ** | Representasi terkompresi |\n",
    "| **Rekonstruksi X̂=Z·Vₖ+μ** | Kembalikan ke ruang piksel |\n",
    "| **Cosine Similarity** | Ukuran kemiripan wajah di ruang PCA |\n",
    "| **MSE/PSNR/SSIM** | Evaluasi kualitas kompresi |\n",
    "| **EDA** | Analisis sebelum, saat, dan setelah PCA |"
   ]
  }
 ]
}
